baseURL = 'https://racing.pahim.org/'
locale = 'en-us'
title = 'Pahim Racing'

[build]
  [build.buildStats]
    enable = true

[module]
  [module.hugoVersion]
    extended = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Engineering the Apex. A Software Engineer's approach to competitive motorsport."
  tagline = "Data in. Performance out."
  author = "Amador Pahim"
  githubURL = "https://github.com/apahim"
  boxboxURL = "https://boxbox.ie"
  contactFormURL = "https://forms.gle/KkeEkg7mHE2BamTL6"
  linkedinURL = "https://www.linkedin.com/in/amadorpahim"

[menus]
  [[menus.main]]
    name = 'Dashboard'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Foundation'
    pageRef = '/foundation'
    weight = 30
  [[menus.main]]
    name = 'Competition'
    pageRef = '/competition'
    weight = 40
  [[menus.main]]
    name = 'Partnerships'
    pageRef = '/partnerships'
    weight = 50
